Notice minimum required reactor-core version
On 3.2.3 for example it could fail in runtime with `NoClassDefFoundError: reactor/core/publisher/FluxOnAssembly$AssemblySnapshot`